name: Auto Update CSV

on:
  schedule:
    - cron: "*/120 * * * *"   # every 120 minutes
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download latest CSV from OneDrive
        run: |
          curl -L -o data.csv "https://houtx-my.sharepoint.com/my?id=%2Fpersonal%2Ftho%5Fle%5Fhoustontx%5Fgov%2FDocuments%2FDocuments%2FChart%2FFire%20CEs&viewid=32b716ef%2D5190%2D43ca%2Da1c5%2D5f6cfe555021?download=1"

      - name: Commit updated CSV
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git config pull.rebase false
          git add assignments_report.csv
          git commit -m "Auto-update CSV"
          git push

